//
// This file was generated by the Eclipse Implementation of JAXB, v3.0.0 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2025.11.21 at 04:59:32 PM EET 
//

@jakarta.xml.bind.annotation.XmlSchema(namespace = "http://com.kfh.assessment.soapmock/courses", elementFormDefault = jakarta.xml.bind.annotation.XmlNsForm.QUALIFIED)
package soapmock.assessment.kfh.com.courses;
